# needed for docker
sudo: required
# services we want pre-installed as soon was we run our build
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  # install google cloud. everything after pipe is install locally on our instance
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  # configures google cloud through following path
  - source $HOME/google-cloud-sdk/path.bash.inc
  # after google sdk is install, we need to install kubectl
  - gcloud components update kubectl
  # after all the inital setup, we need to do authorization with google cloud
  # service-account.json gives access to our google cloud account
  # service-account.json has sensitive information, should not allow anyone to have
  # access to these credentials
  - gcloud auth activate-service-account --key-file service-account.json